### ISSUE TITLE
dnSpy reported an error

### ISSUE THREAD

**Issue by zhangweildlh** [yazdipour/unlimited-ticktick-windows#13]
Hello, I am using dnSpy and following your instructions to modify it. dnSpy reported an error.
![微信截图_20231111012507](https://github.com/yazdipour/unlimited-ticktick-windows/assets/62597291/24bcaad4-31db-4304-a254-40c7ebefe257)

**Comment by yazdipour** [comment]
Reporting this issue as insecure and closing it
