### ISSUE TITLE
Doesnt work...

### ISSUE THREAD

**Issue by ARGONisg** [yazdipour/unlimited-ticktick-windows#14]
createDbFailed, please make sure to run with administrator privileges
Despite running as admin

**Comment by yazdipour** [comment]
Which version are you using?

**Comment by sunayoruu** [comment]
Hello, I'm having the same issue. Versions 5.0.0.2 and 5.0.0.1 both return the "createDbFailed" error, even when running as admin. I get three errors in order: the first two are the attached images, and the third error before it closes out is the text below them. Errors are the same with both 5.0.0.x versions.

I have no issues when going back to version 4.5.8.0. Haven't tested with any other versions.

<img width="702" alt="image" src="https://github.com/yazdipour/unlimited-ticktick-windows/assets/18585631/deb97064-1238-4bd6-b5e7-c9e09ac814cf">
<img width="305" alt="image2" src="https://github.com/yazdipour/unlimited-ticktick-windows/assets/18585631/f1892b2a-11ef-4506-ae48-dd48785fa58c">

> Operation System Version-> 10.0.22621.0 ***** 
> CurrentTime -> 11/14/2023 01:27:48 ***** 
> Locale -> en-US ***** 
> Device Location -> en-US ***** 
> Version ->  ***** 
> Exception Type -> System.NullReferenceException ***** 
> Exception Message -> Object reference not set to an instance of an object. ***** 
> Exception Data -> System.Collections.ListDictionaryInternal ***** 
>  ->  ***** 
>  -> TickTick ***** 
>  -> Void MoveNext() ***** 
>  ->    at ticktick_WPF.App.<TryGetLocalSettings>d__53.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ticktick_WPF.Util.Utils.<LogTaskTimes>d__153.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ticktick_WPF.App.<StartUpSafely>d__45.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ticktick_WPF.App.<OnStartup>d__40.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) ***** 

Thank you for your work, by the way. It's really helped me out.

**Comment by yazdipour** [comment]
Thanks for the details and error logs. 
I try to investigate the issue.

**Comment by hong-tm** [comment]
😂same problem faced with my laptop

**Comment by yazdipour** [comment]
@sunayoruu @hong-tm @ARGONisg One question from all you guys: Did you fresh install it or was it an upgrade from the app?

**Comment by hong-tm** [comment]
> One question from all you guys: Did you fresh install it or was it an upgrade from the app?

mine is used for long time and always upgrade

**Comment by yazdipour** [comment]
Ok, Tried on two other machines was fine! (upgrading within the app.)
I am going to do fresh install, maybe I can catch the issue

**Comment by sunayoruu** [comment]
> Ok, Tried on two other machines was fine! (upgrading within the app.) I am going to do fresh install, maybe I can catch the issue

Thank you for sharing this! I upgraded within the app and then replaced the exe with the downloaded file, and it worked this time.

I'm guessing the issue was due to my app still being on version 4.5.8.0. I had assumed that replacing the exe in the files would force the update itself, I just needed to upgrade within the app before adding your exe file into the directory in Program Files (x86).

Thank you for the help, I'll make sure not to skip the step of upgrading within the app, in the future.

**Comment by yazdipour** [comment]
Thanks for pointing out. I am going to add it in the documentation

**Comment by hong-tm** [comment]
I found out what my real problem is i am using different version of the tick-tick in china version so it is not compatable with this exe file (https://dida365.com/)😂, i have switch to tick-tick now

**Comment by ARGONisg** [comment]
Yess, works now. Thanks 😄
