### ISSUE TITLE
Big guy,can you make a mac version,thank you

### ISSUE THREAD

**Issue by jackey-jiang** [yazdipour/unlimited-ticktick-windows#22]
Big guy, see you crack the software "ticktick" windows version, especially great, I would like to ask, can you make a mac version, I am willing to pay for this, thank you

**Comment by yazdipour** [comment]
Hey Jackey, I do not have a Mac to work on that unfortunately.
I will do that when I get older ;)

**Comment by jackey-jiang** [comment]
Haha, well, that's all we can do :(
