### ISSUE TITLE
How do I use dnSpy to update the code inside of TickTick

### ISSUE THREAD

**Issue by CaffeineAddiction101** [yazdipour/unlimited-ticktick-windows#23]
How do you actually update the code , when i use edit class and compile it just gave me errors for approach 2. Any help would be appreciated. And how do you actually use method 1.
![Screenshot 2024-04-09 162228](https://github.com/yazdipour/unlimited-ticktick-windows/assets/99570820/2ce896dc-ab91-466a-a32f-c5a88c5cfa56)

**Comment by yazdipour** [comment]
Well I don't have direct answer for you. I'm guessing it is setup issue with dnSpy. Not sure! 

I follow 1st approach. And this is my dnspy version if its going to help you.
![image](https://github.com/yazdipour/unlimited-ticktick-windows/assets/8194807/18001e5c-04f8-4cb7-bdcc-3856627e7bff)
