### ISSUE TITLE
Not syncing correctly

### ISSUE THREAD

**Issue by GustaWinnipeg** [yazdipour/unlimited-ticktick-windows#24]
It says I have premium and everything correctly, and I can create multiple lists in the folder and whatnot. But whenever I create more than one list, it shows a warning sign saying "Unsynced lists ", and whenever I open the web version the list, of course, doesn't show.

**Comment by yazdipour** [comment]
Honestly, I am facing the issue. But I am guessing this could be set of limitations from server side. I don't think from the client side I can do anything!
If you have more details, logs please share it.
